artifact_location: file:///Users/grioool/PycharmProjects/optimization-data-analysis/models/mlruns/187133393983073057
creation_time: 1748534969772
experiment_id: '187133393983073057'
last_update_time: 1748534969772
lifecycle_stage: active
name: DenseNet
