artifact_location: file:///Users/grioool/PycharmProjects/optimization-data-analysis/models/mlruns/0
creation_time: 1748534969568
experiment_id: '0'
last_update_time: 1748534969568
lifecycle_stage: active
name: Default
